FROM node:20-alpine AS staging

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g @angular/cli

RUN npm install

COPY . .

RUN npm run build:staging

FROM nginx:alpine AS nginx

COPY nginx-stg.conf  /etc/nginx/conf.d/default.conf

COPY --from=staging /usr/src/app/dist/open-site-system-front-end/ /usr/share/nginx/html

EXPOSE 81
